name: Run tests and build examples
on:
  - push
  - pull_request
env:
  nim-version: "2.2.0"
  libsoundio-win-repo: "https://github.com/SpotlightKid/libsoundio-windows-bin"
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out sources
        uses: actions/checkout@v4
      - name: Nim Runtime Cache
        id: cache-nim
        uses: actions/cache@v4
        with:
          path: ".nim_runtime"
          key: ${{ runner.os }}-nim-${{ env.nim-version }}
      - name: Install Nim
        id: install-nim
        uses: jiro4989/setup-nim-action@v2
        with:
          nim-version: ${{ env.nim-version }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ hashFiles('.nim_runtime/bin/nim*') == '' }}
      - name: Set PATH for Unix
        shell: bash
        run: |
          echo "$(pwd)/.nim_runtime/bin" >> "$GITHUB_PATH"
          echo "$HOME/.nimble/bin" >> "$GITHUB_PATH"
        if: ${{ runner.os != 'Windows' && steps.install-nim.outcome == 'skipped' }}
      - name: Set PATH for Windows
        shell: pwsh
        run: |
          echo "$(Get-Location)\.nim_runtime\bin" >> $Env:GITHUB_PATH
          mkdir -Force ~\.nimble\bin
          (Resolve-Path ~\.nimble\bin).Path >> $Env:GITHUB_PATH
        if: ${{ runner.os == 'Windows' && steps.install-nim.outcome == 'skipped' }}
      - name: Install dependencies
        uses: ConorMacBride/install-package@v1
        with:
          brew: libsoundio
          apt: libsoundio-dev
      - name: Download libsoundio DLL binary (Windows)
        if: runner.os == 'Windows'
        run: |
          git clone -c advice.detachedHead=false  --branch 2.0.1-7 --single-branch --depth 1 "${{env.libsoundio-win-repo}}"
          Copy-Item -Path "libsoundio-windows-bin\win\x64\libsoundio.dll" -Destination "$(Get-Location)"
          Add-Content $env:GITHUB_PATH "$(Get-Location)"
      - name: Update LIBRARY_PATH (macOS)
        if: runner.os == 'macOS'
        run: echo "LIBRARY_PATH=$(brew --prefix)/lib" >> "$GITHUB_ENV"
      - name: Run tests
        run: nimble test -y --verbose
      - name: Build examples (debug)
        run: nimble examples_debug
      - name: Build examples (release)
        run: nimble examples
