name: Run tests and build examples
on: [push, pull_request]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out sources
        uses: actions/checkout@v4
      - name: Install Nim
        uses: jiro4989/setup-nim-action@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install dependencies
        uses: ConorMacBride/install-package@v1
        with:
          brew: libsoundio
          apt: libsoundio-dev
          choco: libsoundio
      - name: Update PATH (Windows)
        if: runner.os == 'Windows'
        run: Add-Content $env:GITHUB_PATH "C:\Program Files\libsoundio\bin"
      - name: Update LIBRARY_PATH (macOS)
        if: runner.os == 'macOS'
        run: echo "LIBRARY_PATH=$(brew --prefix)/lib" >> "$GITHUB_ENV"
      - name: Run tests
        run: nimble test -y
      - name: Build examples (debug)
        run: nimble examples_debug
      - name: Build examples (release)
        run: nimble examples
